services:
  app-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: dev-stage
    volumes:
      - ../../engWordRank:/home/backend/app
    ports:
      - "8000:8000"